spring.output.ansi.enabled: ALWAYS
service:
  name: user-service
  port: 7911
#数据源
spring:
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/micro-service?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    # 最新官方提示支持将com.mysql.jdbc.Driver  改为  com.mysql.cj.jdbc.Driver
    # 或者修改mysql connector版本
    driver-class-name: com.mysql.cj.jdbc.Driver